kind: Pod
apiVersion: v1
metadata: 
  name: counter-test
spec:
  containers:
  - name: test
    image: busybox
    command: ['sh', '-c', 'while [ 1 ]; do wget -qO- http://$COUNTER_SERVICE_SERVICE_HOST:$COUNTER_SERVICE_SERVICE_PORT/counter && echo ""; sleep 2; done']