kind: Deployment
apiVersion:	extensions/v1beta1
metadata:
  name: counter-deployment
  labels:
    app: counter
    version: v2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: counter
      version: v2
  template:
    metadata:
      labels:
        app: counter
        version: v2
    spec:
      containers:
      - name: count
        image: eu.gcr.io/mp-box-dev/hserver
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"