kind: Deployment
apiVersion:	extensions/v1beta1
metadata:
  name: counter-deployment
  labels:
    app: counter
    env: test
spec:
  replicas: 3
  minReadySeconds: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1  
  selector:
    matchLabels:
      app: counter
      env: test
  template:
    metadata:
      labels:
        app: counter
        env: test
    spec:
      containers:
      - name: count
        image: eu.gcr.io/mp-box-dev/hserver:v3
        ports:
        - name: liveness-port
          containerPort: 8080
          hostPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: liveness-port
            httpHeaders:
            - name: X-Liveness
              value: alive
          initialDelaySeconds: 3
          periodSeconds: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"