apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: counterservices.counter.richaud.net
spec:
  group: counter.richaud.net
  names:
    kind: CounterService
    listKind: CounterServiceList
    plural: counterservices
    singular: counterservice
  scope: Namespaced
  version: v1alpha1
  additionalPrinterColumns:
  - name: Backends
    type: integer
    format: int32
    description: The number of backends serving the counter
    JSONPath: .spec.backends
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            backends:
              type: integer
              minimum: 1
              maximum: 10