kind: Service
apiVersion: v1
metadata:
  name: counter-service
  labels:
    app: counter
spec:
  selector:
    app: counter
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer